### ISSUE TITLE
[24.04 ISO] Set nvidia-drm.modeset=1

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/iso#333]
The image has modules_load=nvidia and nvidia-drm.modeset=0. nvidia-drm.modeset should be 1 {nvidia-drm.modeset=1)

**Comment by XV-02** [comment]
Changing the `nvidia-drm.modeset` kernel param to `1`, allows cosmic-greeter/cosmic-session to function. 

However, in testing, I cannot launch native cosmic GUI applications [(output of an attempt to run cosmic-term)](https://github.com/user-attachments/files/16316096/Cosmic-Term_attempt.log) The errors seem to be consistent for all the cosmic applications I've been trying.

Additionally, I think I'm seeing a phantom display, which is resulting in the installer presenting on a non-existent display when the live session is entered. I pulled 
[the display list from `cosmic-randr`](https://github.com/user-attachments/files/16316115/Cosmic-Randr_list.log).

**Comment by XV-02** [comment]
I can confirm successful installation of 24.04 from debug ISO 168 with `nvidia-drm.modeset=1`, and that there is a phantom display as shown in the cosmic-randr output. Issues with native cosmic GUI applications seem to be limited to the live session, as they work on the installed session.

**Comment by Drakulix** [comment]
> However, in testing, I cannot launch native cosmic GUI applications [(output of an attempt to run cosmic-term)](https://github.com/user-attachments/files/16316096/Cosmic-Term_attempt.log) The errors seem to be consistent for all the cosmic applications I've been trying.

This looks driver problems. Does the iso system have the `egl-wayland` installed?

**Comment by XV-02** [comment]
`libnvidia-egl-wayland1` _is_ present.

**Comment by mmstick** [comment]
Done via https://github.com/pop-os/iso/pull/335

**Comment by JamesJieranShen** [comment]
> Changing the `nvidia-drm.modeset` kernel param to `1`, allows cosmic-greeter/cosmic-session to function.
> 
> However, in testing, I cannot launch native cosmic GUI applications [(output of an attempt to run cosmic-term)](https://github.com/user-attachments/files/16316096/Cosmic-Term_attempt.log) The errors seem to be consistent for all the cosmic applications I've been trying.
> 
> Additionally, I think I'm seeing a phantom display, which is resulting in the installer presenting on a non-existent display when the live session is entered. I pulled [the display list from `cosmic-randr`](https://github.com/user-attachments/files/16316115/Cosmic-Randr_list.log).

Hello! I am trying to install the PopOS 24.04 Cosmic alpha 1 ISO (ISO 188 according to grub) and it seems that the issue related to cosmic-term and other cosmic applications is still present. I am unable to open cosmic-term in the live session, and the traced output when attempting to do so is the same for as the one quoted above. However, I am indeed no longer seeming a phantom display in `cosmic-randr`. I can also confirm via `cat /sys/module/nvidia_drm/parameters/modeset` that the `nvidia-drm.modeset` is indeed set to 1. I believe #338 is referring to the same issue. 

It seems that this issue also affects running the installer itself -- during boot, the installer does pop up. However, after language selection and clicking Continue, the app closes.

Thanks for all the great work!
